language: bash
sudo: required
services:
  - docker

before_install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build --no-cache -t x11apps/pycharm-community .
        - docker push x11apps/pycharm-community
